### ISSUE TITLE
Metagenomic option

### ISSUE THREAD

**Issue by sxh1136** [ku-cbd/PhageBoost#12]
Hi there,

I was wondering what the correct paramaeter for the metagenomic option is? I asks for an interger so should I just put "--meta 1". 

Also specifying the -j flag doesn't seem to change anything about parallelisation, with everything still running on one core.

Thanks for your help in advance
Stan

**Comment by sxh1136** [comment]
Thanks for your quick reply, thats very useful! 

Also seperate question: I'm planning to run both this program and phigaro in succession on some bacterial chromosomes. Do you think it matters which order I run the tools?

**Comment by kkpsiren** [comment]
sorry for the slower reply this time :) 
Order will not matter if you use the same reference input for both as the then the genome should stay unchanged. If you'd like to assign the hmms to the phage fasta you get from PhageBoost, then you could run phigaro on those files.
